#!/bin/bash
# GitHub Repository Setup Instructions for HW10 Project
# Run this script after creating a new repository on GitHub

echo "================================"
echo "GitHub Repository Setup"
echo "================================"
echo ""
echo "PREREQUISITES:"
echo "1. Create a new repository on GitHub at https://github.com/new"
echo "   - Name: comp484-project2-hw10"
echo "   - Public or Private (your choice)"
echo "   - Do NOT initialize with README, .gitignore, or license"
echo ""
echo "2. Have your GitHub credentials ready"
echo ""
echo "STEPS TO PUSH:"
echo ""
echo "1. Set the new remote origin:"
echo "   git remote set-url origin https://github.com/SakoPolis/comp484-project2-hw10.git"
echo ""
echo "2. Push to GitHub:"
echo "   git push -u origin main"
echo ""
echo "When prompted, use one of these authentication methods:"
echo "  - Personal Access Token (PAT) - recommended"
echo "  - GitHub username and password"
echo "  - SSH key (if configured)"
echo ""
echo "CREATE A PERSONAL ACCESS TOKEN:"
echo "1. Go to https://github.com/settings/tokens/new"
echo "2. Select 'repo' scope"
echo "3. Generate and copy the token"
echo "4. Use the token as the password when git prompts"
echo ""
echo "================================"
echo "Your repository is ready to push!"
echo "================================"
